server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:abc123!%40%23@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
      enabled: true


cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY}
  api_secret: ${API_SECRET}