server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: ad123456

app:
  services:
    file:
      url: http://localhost:8084/file


